-- Migration: Add 'order_number' column and backfill existing data

-- 1. Add order_number column (nullable by default for now, then we fill it)
-- We use GENERATED BY DEFAULT AS IDENTITY which auto-increments for new rows.
ALTER TABLE "public"."orders" 
ADD COLUMN IF NOT EXISTS "order_number" BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 2. Backfill existing orders
-- We assign numbers 1..N based on created_at ASC to keep history sequential.
-- This CTE calculates the proposed number for each existing order.
WITH sorted_orders AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY created_at ASC) as rn
  FROM "public"."orders"
)
UPDATE "public"."orders"
SET "order_number" = sorted_orders.rn
FROM sorted_orders
WHERE "orders"."id" = sorted_orders.id;

-- 3. Sync the sequence
-- Important: Ensure the sequence starts after the last backfilled number.
-- Note: 'orders_order_number_seq' is the default naming convention, 
-- but using pg_get_serial_sequence is safer if supported.
SELECT setval(pg_get_serial_sequence('orders', 'order_number'), (SELECT MAX(order_number) FROM "public"."orders"));
