class PostModel {
  final String? id;
  final String? systemId;
  final String userId; // Maps to author_id
  final String? userName; // fetched via join
  final String? userPhone;
  final String content;
  final List<String> imageUrls;
  final String postType;
  final int likesCount;
  final DateTime createdAt;

  // Auxiliary
  final List<dynamic> comments;

  PostModel({
    this.id,
    this.systemId,
    required this.userId,
    this.userName,
    this.userPhone,
    required this.content,
    this.imageUrls = const [],
    this.postType = 'general',
    this.likesCount = 0,
    required this.createdAt,
    this.comments = const [],
  });

  factory PostModel.fromJson(Map<String, dynamic> json) {
    return PostModel(
      id: json['id'] as String?,
      systemId: json['system_id'] as String?,
      userId: json['author_id'] as String? ?? '',
      userName: json['profiles']?['full_name'] as String?, // Assuming join: profiles(full_name)
      userPhone: json['profiles']?['phone_number'] as String?,
      content: json['content'] as String? ?? '',
      imageUrls: (json['image_urls'] as List?)?.map((e) => e.toString()).toList() ?? [],
      postType: json['post_type'] as String? ?? 'general',
      likesCount: json['likes_count'] as int? ?? 0,
      createdAt: DateTime.tryParse(json['created_at'] ?? '') ?? DateTime.now(),
      comments: json['comments'] as List<dynamic>? ?? [], // If joined
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // 'id': id, // Usually generated by DB
      'system_id': systemId,
      'author_id': userId,
      'content': content,
      'image_urls': imageUrls,
      'post_type': postType,
      'likes_count': likesCount,
      'created_at': createdAt.toIso8601String(),
    };
  }
}
