name: Flutter Build & Test

on:
  push:
    branches: [ "main", "django_api" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate Localizations
        run: flutter gen-l10n

      - name: Analyze Project Source
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      - name: Build APK (Release)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
